// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCerGQziM7dofgsc79QX5F6WOGlPsnZAfs',
    appId: '1:903835076044:web:a6dfc951a32159dc3c4969',
    messagingSenderId: '903835076044',
    projectId: 'daily-mcq-4ed8d',
    authDomain: 'daily-mcq-4ed8d.firebaseapp.com',
    storageBucket: 'daily-mcq-4ed8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaz7f3argjtAHj2JOn7UzsanVvompdiEA',
    appId: '1:903835076044:android:4dea49bbc0401aa63c4969',
    messagingSenderId: '903835076044',
    projectId: 'daily-mcq-4ed8d',
    storageBucket: 'daily-mcq-4ed8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW8XS0RMD38q19IL-NmwIDADOUJjINIkA',
    appId: '1:903835076044:ios:29854c8a4e9ee2b73c4969',
    messagingSenderId: '903835076044',
    projectId: 'daily-mcq-4ed8d',
    storageBucket: 'daily-mcq-4ed8d.appspot.com',
    iosBundleId: 'com.example.dailyMcqMvvm',
  );
}
